### ISSUE TITLE
How to use CUDA enabled arrow-cpp from another recipe?

### ISSUE THREAD

**Issue by pearu** [conda-forge/arrow-cpp-feedstock#136]
Consider https://github.com/conda-forge/pyarrow-feedstock/pull/101 where the meta.yaml contains:
```
outputs:
  - name: pyarrow
<snip>
    requirements:
<snip>
      host:
        - arrow-cpp {{ version }}
<snip>
      run:
        - arrow-cpp {{ version }}
<snip>
      run_constrained:
        - arrow-cpp-proc * {{ build_ext }}
```
and I would expect that `build_ext == cuda` in the last line would force to pick up `arrow-cpp` packages (in host and run sections) with `*_cuda` build strings.
But as seen in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=150318&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=937c195f-508d-5135-dc9f-d4b5730df0f7 the `arrow-cpp` with `*_cpu` build string is used.

One possibility would be to specify
```
        - arrow-cpp {{ version }} *_{{ build_ext }}
```
but that would make the usage of `arrow-cpp-proc` unnecessary.

Hence the question in the title..

**Comment by jakirkham** [comment]
Do you have a PR to look at somewhere? It will be easier to advise.

**Comment by pearu** [comment]
Yes, it is https://github.com/conda-forge/pyarrow-feedstock/pull/101

**Comment by pearu** [comment]
The problem with the above example seems to be that `run_constrained` applies to `run` section only and not to `host` section. Using
```
      host:
        - arrow-cpp {{ version }} *_{{ build_ext }}
```
fixes the issue.

**Comment by jakirkham** [comment]
Would just do...

```yaml
      host:
        - arrow-cpp-proc * {{ build_ext }}
      run_constrained:
        - arrow-cpp-proc * {{ build_ext }}
```

Plus whatever else goes in those and other sections.

**Comment by pearu** [comment]
Closing with the following solution:
```
outputs:
  - name: pyarrow
<snip>
    requirements:
<snip>
      host:
        - arrow-cpp {{ version }}
        - arrow-cpp-proc * {{ build_ext }}
<snip>
      run:
        - arrow-cpp {{ version }}
<snip>
      run_constrained:
        - arrow-cpp-proc * {{ build_ext }}
```
